kind: Service
apiVersion: v1
metadata:
  name: ostoy-microservice
  labels:
    app: ostoy
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: ostoy
    deployment: ostoy-microservice
