kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ostoy
  labels:
    app: ostoy
    app.kubernetes.io/component: ostoy
    app.kubernetes.io/instance: ostoy
spec:
  to:
    kind: Service
    name: ostoy
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
