apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ostoy
  namespace: openshift-gitops
spec:
  destination:
    namespace: ostoy
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app
    repoURL: 'https://github.com/tosin2013/ostoy.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true